### ISSUE TITLE
"atob is not defined" - possible fix included

### ISSUE THREAD

**Issue by jamesmortensen** [component/data-uri-to-blob#3]
I installed this as a npm package in node-webkit and get the following error when trying to convert a data imageUrl to a blob:

```
atob is not defined
```

I modified the index.js file to make the following change from:

```
 var bytes = atob(data);
```

and changed it to:

```
 var bytes = window.atob(data);
```

This seems to resolve the issue.

---

Since I'm not familiar with component, I'm not sure if that change would cause any problems, so I thought I'd just report it instead.  Hope this helps!

**Comment by jonathanong** [comment]
is `window` not the global object in node-webkit? what is then?

**Comment by jamesmortensen** [comment]
@jonathanong window is global in the content layer portion of node-webkit, but within Node modules it is not global.  If you run `atob` in the dev tools, in either Chrome or in node-webkit, atob is defined as a native function.  However, within Node modules it is undefined.

This is the case whether the Node module runs in pure Node.js or in node-webkit.  Hope this helps.

**Comment by dmitryrn** [comment]
And what to do in node.js???
